enables = true
baseURL = "https://paarthmadan29.github.io/"
title = "Paarth Madan"
subtitle = "Documenting thoughts, experiments, and learnings."
theme = "PaperMod"

[[params.profileMode.buttons]]
name = "Posts"
url = "/"

[pagination]
  pagerSize = 10

paginate = 10

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowSummary = true

[menu]
  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 2
    
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3


[[params.socialIcons]]
name = "github"
url = "https://github.com/paarthmadan29"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/paarth_madan"

[[params.socialIcons]]
name = "X"
url = "https://x.com/paarth_madan"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

mainSections = ["posts"]
